balderdashy/sails-docs

- concepts/ORM/ORM.md
Linking to _Connections_ section of this page.
> Added link for connection configuration.

- reference/sails.config/sails.config.session.md
If there is any misktake, please correct me ;)
> Add config.session.key description

- reference/sails.config/sails.config.views.md
Adds documentation for the property added in https://github.com/balderdashy/sails/pull/2304
> add extension property

- concepts/Routes/URLSlugs.md
removed indentation to mirror other code blocks, it fixes indentation on the website.
> Updated URLSlugs.md - indentation

- concepts/ORM/model-settings.md
...on big databases. Fixes balderdashy/sails#2534.
> Note about 'alter' setting on models taking a long time to complete

- concepts/Deployment/Hosting.md
See https://github.com/balderdashy/sails-docs/pull/424.
> Add "Sails.js and Heroku" to Hosting.md

- concepts/extending-sails/Adapters/adapterList.md
- contributing/intro-to-custom-adapters.md
- status/plugins/adapters.js
> Add waterline-orientdb adapter

- anatomy/myApp/api/hooks/myHook/index.js.md
- anatomy/myHook/index.js.md
I know that this need more love, but I wanted to put the first stone
> added hook anatomy documentation

- concepts/File Uploads/File Uploads.md
> Removed html commented out tags that affected markdown loyout

- concepts/extending-sails/Adapters/adapterList.md
- contributing/intro-to-custom-adapters.md
- status/plugins/adapters.js
> Update OrientDB adapter reference

- contributing/adapter-specification.md
Update adapter-specification.md to include the new SQL interface.
Details about this on: balderdashy/waterline-adapter-tests#40
> Add SQL interface

- concepts/Routes/RouteTargetSyntax.md
Prompted by balderdashy/sails#2841
> Add extra note to RouteTargetSyntax.md about wildcards

- anatomy/myApp/tasks/register/register.md
In conjunction with #2814, include information for running custom grunt tasks.
> Update register.md for PR #2814

- anatomy/myApp/tasks/register/prod.js.md
In conjunction with #2814, include information for running custom grunt tasks.
> Update prod.js.md for PR #2814

- concepts/Assets/TaskAutomation.md
In conjunction with #2814, include information for running custom grunt tasks.
> Update TaskAutomation.md for PR #2814

- reference/waterline/models/create.md
- reference/waterline/models/destroy.md
- reference/waterline/models/find.md
- reference/waterline/models/findOne.md
- reference/waterline/models/findOrCreate.md
- reference/waterline/models/models.md
- reference/waterline/models/stream.md
- reference/waterline/models/update.md
I noticed that there was some inconsistency in the white space in the model examples.
> Fix inconsistent white space in the model docs

- support/irc/grabClient.md
> Markdown error

- concepts/Testing/Testing.md
I'm guessing there are a lot of sails users, who are not quite sure on how to run test and make it work with their models and controllers, i was lost the first time too. As you can see in this question in SO:
[Sails.js: How to actually run tests](https://stackoverflow.com/questions/26837522/sails-js-how-to-actually-run-tests/29804922#29804922).
So i added some details on how to do this, and how to run your mocha test using coffeeScript too.
I hope this PR gets accepted and can help new users.
PST: If i made a mistake in the changes please let me know and i'll fix them.
> Added info on how to run your test

- reference/websockets/sails.io.js/io.socket.on.md
Added description of 'connect' and 'disconnect' events of sails.io with examples
> Added 'connect' and 'disconnect' events of sails.io

- concepts/Policies/SailsAndPassport.md
That space doesn't seem to be a problem on Github markdown but on the [page](http://sailsjs.org/#!/documentation/concepts/Policies) it makes the link ~~not work~~ not look very good.
> Removed space

- concepts/Configuration/Configuration.md
Changed "to configuration" to "to configure"
> Minor typo fix

- concepts/Configuration/Configuration.md
> repetetive ->repetitive

- concepts/Views/Layouts.md
Add an example of specifying custom layout with the view in the response of a controller action.
> Add example of including layout in a controller res

- concepts/extending-sails/Adapters/adapterList.md
Hello
I published an adaptor for FileMaker. It passes all the relevant tests for the semantic interface. It skips a few of the type tests that are irrelevant to it.  It's currently in use in one projects. So it's relatively fresh, and likely some rough edges.
Thanks
Todd
> New Adaptor For FileMaker

- getting-started/NewToNode.md
Fix the anchors:
* I have Mac OSX
* I have Linux
* I have Windows
> fix anchors in getting-started/NewToNode.md

- concepts/ORM/Associations/ManytoMany.md
Delete the broken link to waterline association doc
> Update link to Waterline doc

- concepts/Controllers/Controllers.md
https://en.wiktionary.org/wiki/principal#Adjective
> Fix documentation typo

- concepts/Policies/Policies.md
Reading through the docs more thoroughly – will try to find any errors or typos and fix them.
> Fix 'apply a policy to a specific controller action' typo

- reference/blueprint-api/Create.md
- reference/blueprint-api/Destroy.md
- reference/blueprint-api/Update.md
- reference/blueprint-api/blueprint-api.md
Hi,
This branch fixes a few incorrectly leveled headings.
> Fix several headings

- FAQ.md
- concepts/ORM/Attributes.md
- concepts/ORM/Lifecyclecallbacks.md
- concepts/ORM/Models.md
- concepts/ORM/Querylanguage.md
- concepts/ORM/model-settings.md
- concepts/Routes/RouteTargetSyntax.md
- concepts/Security/ContentSecurityPolicy.md
- concepts/Security/DDOS.md
- concepts/Security/StrictTransportSecurity.md
- concepts/Testing/Testing.md
- concepts/Views/Partials.md
- concepts/Views/ViewEngines.md
First and foremost, I didn't even have to look up how to spell `miscellanea`. That should establish my credentials here.
Included are a handful of mini-changes including (but not limited to):
* :skull: Death to broken links (e.g., 0124f5f)
* :mortar_board: Tidying up of some (english) syntax oopsies (e.g., fbd8fcc)
* :computer: Replacement of a screenshot of code with... well, code (cbc2c51)
I also rearranged a few sentences here and there, and expanded on a few terms that were not explicitly defined. (E.g., 4c2778e, 27916e9, 465ba9c)
Sorry if some of this is overstepping boundaries (I know, I know- we just met), but I had some pretty :+1: :pizza: for lunch, and I'm all-around [very stoked right nyaw](http://www.theonion.com/video/report-most-college-males-admit-to-regularly-getti-14386).
> miscellanea 

- anatomy/myApp/config/locales/_README.md.md
- concepts/Custom Responses/Custom Responses.md
- concepts/File Uploads/File Uploads.md
- concepts/Internationalization/Locales.md
- concepts/Security/CORS.md
- concepts/extending-sails/Hooks/hookspec/initialize.md
- concepts/extending-sails/Hooks/hookspec/routes.md
- reference/blueprint-api/Create.md
- reference/blueprint-api/Destroy.md
- reference/blueprint-api/Find.md
- reference/blueprint-api/FindOne.md
- reference/blueprint-api/Populate.md
- reference/blueprint-api/Update.md
- reference/blueprint-api/blueprint-api.md
- reference/req/req.options/req.options.md
- reference/req/req.options/req.options.values.md
- reference/req/req.options/req.options.where.md
- version-notes/0.10.x/Changelog0.10x.md
Hi,
This fixes many details:
- set language in a few code blocks
- fix json errors
- remove useless spaces in a few pages
- more consistency between pages in reference/blueprint-api
> Fix little errors

- README.md
makes the updating process clearer in the readme, per @rachaelshaw's suggestion in #536
> update readme re: #536

- concepts/extending-sails/Hooks/installablehooks.md
Fixing a few broken links I came across.
> Fix hook spec links

- concepts/Deployment/FAQ.md
See https://github.com/balderdashy/sails/issues/3099#issuecomment-126047866.
> Document the memory leak in default sessions

- concepts/Deployment/Scaling.md
https://en.wikipedia.org/wiki/Load_balancing_(computing)
> Updated with correct wiki link

- getting-started/NewToNode.md
Hey all,
Tried to be more accurate describing node, since we already have an in-depth one above.  also removed some trailing whitespace.
> add accurate description of node.js

- reference/blueprint-api/Find.md
I guess this is how it should be...
> Making JSONP callback string instead of number

- concepts/Security/CSRF.md
Hello,
I think I found and corrected a typo in the doc.
Best,
Guillaume Leclerc
> fix link in CSRF.md

- concepts/ORM/Associations/OneWayAssociation.md
An irrelevant camel case spotted.
> Unnecessary camel case

- concepts/Deployment/Hosting.md
NodeJitsu is no longer providing hosting.
> Remove NodeJitsu

- concepts/Assets/DisablingGrunt.md
Please add this so someone else doesn't blow 4 hours trying to figure out why their sails assets just keep throwing `404` :\
> Adding additional note about removing Gruntfile.js.

- reference/websockets/sails.io.js/sails.io.js.md
depencencies should be dependencies
> Fix directory typo in sails.md.js

- reference/waterline/models/destroy.md
Added a destroy() example since I wasn't sure about destroying multiple.
> Added destroy example to clarify deleting multiple records

- reference/waterline/populated-values/populated-values.md
The "or" should go at the end of the bullet point. Just a little confused reading it...
> Simple grammar mistake

- anatomy/myApp/config/locales/de.json.md
Fixed German translation
`Wilkommen` > `Willkommen`
> Fixed German translation

- reference/cli/sailsgenerate.md
Describe how to use Coffeescript in sails, also help to solve https://github.com/balderdashy/sails/issues/3479 and future related questions
> Add documentation for how to use Coffeescript in sails projects

- reference/sails.config/sails.config.sockets.md
Update socket adapter options with changes on version 11
> Update socket adapter options with changes on version 11

- reference/sails.config/sails.config.log.md
I added `inspect` and `custom` as parameters and added an example of using winston as a custom logger.
> Added additional parameters and examples to cover using a custom logger.

- concepts/ORM/Models.md
There are a lot of confusion about this topic going on over the stackoverflow and xchat. I thought I could clear things up here.
> Add custom attribute note

- reference/waterline/models/query.md
Add a sentence to clarify model.query() method won't return a promise.
> Model.query() won't return a promise

- concepts/Internationalization/Locales.md
Fixes #622
I've moved the snippet to [this issue](https://github.com/balderdashy/sails-docs/issues/623) so we can remember to write a guide about it.
> Remove commented out code

- reference/websockets/resourceful-pubsub/publishCreate.md
using socket.get and socket.on gave an uncaught reference error: socket not defined. Replacing it with io.socket.get and io.socket.on solved the issue. 
PS: I'm a beginner working on sails v0.11.3
> io.socket.get in place of socket.get

- reference/waterline/models/models.md
> updates waterline url

- reference/sails.config/miscellaneous.md
> updated links

- reference/waterline/records/toJSON.md
There is a lot of confusion regarding this in stackoverflow and xchat regarding this topic. This will clear things up.
> Provide custom attribute example

- reference/waterline/queries/populate.md
Support for array on populate was added on waterline v0.11.0 https://github.com/balderdashy/waterline/pull/1190/files
> Array on populate

- reference/websockets/websockets.md
[Broken link exists](http://sailsjs.org/documentation/reference/web-sockets) so I fixed it
> Correct resource from sails.io.js to Socket Client

- concepts/ORM/Attributes.md
- reference/waterline/waterline.md
Two minor patches because Sunday.
> Sunday cleaning

- reference/websockets/sails.sockets/sails.sockets.leave.md
fixed copy pasted description from join
> fixed copy pasted description from join

- reference/websockets/sails.sockets/sails.sockets.subscribers.md
> changed app by sails

- concepts/extending-sails/Hooks/hookspec/initialize.md
Modified lines:
* code snippets for http://sailsjs.org/documentation/concepts/extending-sails/hooks/hook-specification/initialize#?hook-events-and-dependencies.
> add closing paranthesis on the code snippets

- concepts/Deployment/Deployment.md
> minor documentation typo fix

- concepts/ORM/Attributes.md
Update the options to reflect what is in Waterline [types](https://github.com/balderdashy/waterline/blob/master/lib/waterline/utils/types.js)
> Update Attributes Options list

- concepts/Sessions/sessions.md
http://sailsjs.org/documentation/concepts/sessions
> headers not displaying correctly

- reference/waterline/models/models.md
I feel that this needs to be done in all the docs with thenable objects. Helps newbies start in the right direction as I feel it is much easier to control code with promises
> Add promise based model call

- concepts/File Uploads/File Uploads.md
Changed resolving directory, because it was wrongly resolving it to absolute '/assets/images/ and should be relative to sails directory based on [path.resolve](https://nodejs.org/api/path.html#path_path_resolve_from_to)
> Update uploading to custom directory

- reference/waterline/models/query.md
Had to google how to do the prepared statement staff using models ```.query()``` method. Thought it would be more comfortable to put it in docs.
> Added Prepared Statement Example

- concepts/Middleware/Middleware.md
> Fix useless link to docs on configurable middleware

- concepts/Logging/Logging.md
Documentation is not saying how to really log something (or I miss it)
> Add usage section

- reference/cli/sailsdebug.md
Add a part to explain how to launch node-inspector with sailsjs app with tips if node-inspector is slow
> add explanations to debug app with node-inspector

- README.md
I will translate these sails document to Chinese version, and now fork it to my domain.
> Add the Chineses translation version links in the above table

- concepts/Middleware/Middleware.md
As you are using [http-auth](http://http-auth.info), I updated sample with it.
It causes problems like this:
- http://stackoverflow.com/questions/37615822/how-to-use-http-auth-with-sails/37634183#37634183
- https://github.com/balderdashy/sails/issues/2834
> Update sample with http-auth module

- reference/application/events.md
Removed second sentence "several apps before they even encounter application events."
> Removed redundant sentence with typo

- concepts/File Uploads/File Uploads.md
Added a line of code which sets the downloaded file to be the same name as the user uploaded.
> Update File Uploads.md

- concepts/Realtime/Realtime.md
I had this problem and found the answer here: http://stackoverflow.com/a/38775719/5219886
> Correct the example `hello` controller method

- reference/res/res.md
Table with contents of reponse object has nothing to do with requests
> Removed invalid table description

- reference/res/res.md
- reference/waterline/models/query.md
Use of Promises , Generators and Yield
> Webpack support

- concepts/ORM/model-settings.md
Hey guys, if anyone has a moment to review for typos/falsehoods, I'd really appreciate it (wrote this kind of quickly).
> Giving "Model settings" some love

- reference/waterline/populated-values/populated-values.md
It's "Robb" not "Rob." Tsk Tsk Tsk
> Corrected misspelling of beloved character's name.

- concepts/extending-sails/Adapters/adapterList.md
Just a small correction. (only a letter whoa, ok)
> Update to adapterList.md

- reference/waterline/models/query.md
**node:** 4.4.5
**sails:** 12.1
**sails-mysql:** 11.5
Tried the example and did not work, had to change it to my proposed change and it works.
> [Update] Prepared statement seems out of date

- concepts/Middleware/Middleware.md
update example so that it matches https://github.com/balderdashy/sails-generate/commit/06e464d316860b0d197f46a3b43e7bda0a68d224
> update http middleware example to match latest Sails v1 

- concepts/Realtime/On the client.md
- concepts/Realtime/Realtime.md
- reference/websockets/sails.io.js/io.socket.md
- reference/websockets/sails.io.js/sails.io.js.md
> missing = character in script tag

- reference/blueprint-api/Populate.md
closes https://github.com/balderdashy/sails-docs/issues/775
> closes https://github.com/balderdashy/sails-docs/issues/775

- concepts/ORM/model-settings.md
Just trying to help and give my 2 cents ;)
Adding another example for changing the default model settings, since the one provided was referring to the settings for a particular model.
Fix small typo.
Give a more meaningful headline.
> short review 

- upgrading/To1.0.md
> typo constraing => constraint

- concepts/Blueprints/Blueprint Actions.md
Changes as per comment by @rachaelshaw 
https://github.com/balderdashy/sails-docs/pull/592#issuecomment-267881022
> Add section for overriding blueprint actions

- concepts/extending-sails/Hooks/hookspec/routes.md
Added missing closing curly bracket and added missing whitespace
> Fix - missing closing curly bracket

- reference/res/res.redirect.md
I use this method with the 'statusCode' parameter to correct 404 errors (for example).
I hope this information could help some.
> Update res.redirect.md (statusCode)

- concepts/File Uploads/File Uploads.md
Hi,
While working on the french translation of sails-docs : https://github.com/marrouchi/sails-docs-fr
I've noticed there is a content that appears twice in this file.
Regards,
> Delete duplicate paragraphs

- README.md
Hi,
I've started today on working it https://github.com/marrouchi/sails-docs-fr
> Add French translation repo

- concepts/ORM/Models.md
I took the initiative to improve things. I hope it's interesting enough.
> Minor changes

- concepts/Assets/TaskAutomation.md
A few typos were discovered, and I didn't want to leave them be.
> Correct typos

- reference/sails.config/sails.config.cors.md
> [patch] Fixed Cors link

- concepts/ActionsAndControllers/ActionsAndControllers.md
> Update ActionsAndControllers syntax errors

- concepts/ActionsAndControllers/ActionsAndControllers.md
> Actions controller fix duplicating

- security/SAILS-SECURITY-POLICY.md
I believe it's supposed to be .com instead of .io for the address
> Documented email address bounces

- reference/blueprint-api/blueprint-api.md
Simple Code Highlighting to a file path Added :)
> Code Highlighting to a file path Added

- reference/waterline/models/query.md
Fix spelling error: Waterine to Waterline line #11
> Fix spelling error

- concepts/Custom Responses/AddingCustomResponse.md
Simply added a javascript header to the code to ensure javascript syntax highlighting.
Makes it easier for us to read. :)
> Update AddingCustomResponse.md-Syntax Highlighting

- upgrading/upgrading.md
> Added to-v-1-0

- tutorials/typeScript.md
The file needs to be .ts instead of .js
People got confused: https://gitter.im/balderdashy/sails?at=59d8fc34bbbf9f1a3832f0b5
> The file needs to be .ts instead of .js

- anatomy/api/helpers/helpers.md
> Fixed Broken Link

- concepts/Deployment/Hosting.md
- faq/faq.md
This was already merged into master with #875, just wanted to see if we could get it added to the 1.0 documentation.
> added nanobox as a hosting option. added nanobox to faq guides

- reference/waterline/models/addToCollection.md
- reference/waterline/models/avg.md
- reference/waterline/models/create.md
- reference/waterline/models/createEach.md
- reference/waterline/models/destroy.md
- reference/waterline/models/find.md
- reference/waterline/models/findOne.md
- reference/waterline/models/models.md
- reference/waterline/models/removeFromCollection.md
- reference/waterline/models/replaceCollection.md
- reference/waterline/models/stream.md
- reference/waterline/models/sum.md
- reference/waterline/models/update.md
Updated addToCollection reference to use `await` instead of `then` and `catch`
> Updated waterline models reference to use await instead of callbacks or .then / .catch

- reference/waterline/models/find.md
Fixed missing `await` in `User.find()`
> Fixed missing await in User.find()

- concepts/ORM/Lifecyclecallbacks.md
Reverts balderdashy/sails-docs#853  (see review- just a few things to knock out first)
> Revert "Update Lifecyclecallbacks.md with error handling"

- anatomy/views/homepage.ejs.md
- anatomy/views/layout.ejs.md
- concepts/Views/ViewEngines.md
- concepts/Views/Views.md
Reverts balderdashy/sails-docs#917
@davidjb Would you mind resubmitting this on the 1.0 branch?
> Revert "Update URLs to new EJS locations"

- anatomy/views/layouts/layout.ejs.md
- anatomy/views/pages/homepage.ejs.md
- concepts/Views/ViewEngines.md
- concepts/Views/Views.md
This includes the new website and new code repository (which apparently
changed on account of EJS v2).
Redone PR after #917, now based on branch `1.0`.  
Perhaps it'd you could update the docs on making PRs (https://github.com/balderdashy/sails-docs#contributing-to-the-sails-docs) as the docs say to send PRs to `master` (unless related to a unreleased feature, which this isn't as it's just a fix).  Otherwise, it's confusing for people wanting to contribute.
> Update URLs to new EJS locations

- reference/sails.config/miscellaneous.md
Resubmitted this to 1.0 as requested by @mikermcneil
> Minor grammatical fix

- concepts/Security/CORS.md
From 0.X to 1.X the configuration for CORS has moved from cors.js to security.js
> Update CORS.md link from cors.js to security.js

- concepts/ORM/Querylanguage.md
I'm just adding the ] and } forgotten, to close the queries in the right way.
> missing ] and }

- reference/waterline/queries/sort.md
> Update sort.md - Code example typo

- concepts/ORM/Models.md
It's early in the morning so let me know if I'm misreading this somehow, but I'm fairly certain this is what you _meant_ to convey by this example.
> Fix custom model methods example

- concepts/extending-sails/Adapters/customAdapters.md
Modify informtion => information
> Fix spelling mistake on customAdaptes.md

- concepts/Programmatic Usage/Programmatic Usage.md
> Update Programmatic Usage.md

- concepts/ORM/standalone-usage.md
Tweaks. 
I found this section to have a lot of unclear phrasing, so there's quite a bit of rewording in this PR. It's _definitely_ possible that I've misunderstood ideas and rephrased in a way that loses the intended meaning. Let me know!
> Grammar and rephrasing

- concepts/extending-sails/Custom Responses/Custom Responses.md
> Update Custom Responses.md

- concepts/Programmatic Usage/Tips and Tricks.md
Switching words, fixing typos.
> Update Tips and Tricks.md

- concepts/Security/CORS.md
Mostly punctuation fixes. Some changes made to wording, but more for flow than clarity.
> Punctuation and readability

- anatomy/config/security.js.md
> [misc] Fix broken [Security > CORS] & [Security > CSRF] links

- contributing/issue-contributions.md
- Updated to recommend submitting all issues to the main Sails repo
- Reworded some of the non-examples for clarity and Mr. Rogers-ation
- Switched from numbered to un-numbered lists (I see that only the biggest points were numbered in the markdown, but the page was generating all bullets as numbers, and it was kind of overwhelming)
- Minor rewording and punctuation
> [misc] issues

- contributing/core-maintainers.md
Mike's suggestions and a couple of tweaks.
> [misc] updates to core maintainers

- contributing/contributing-to-the-documentation.md
A couple of word changes; also, removed references to the nonexistent table of docs translation projects.
> [misc] updates to docs contribution

- contributing/code-submission-guidelines/writing-tests.md
Minor word swaps and punctuation updates; sentence-case.
> [misc] Small changes to Writing Tests

- contributing/code-submission-guidelines/sending-pull-requests.md
> [misc] code submission review

- contributing/code-submission-guidelines/best-practices.md
> [misc] best practices

- contributing/code-submission-guidelines/code-submission-guidelines.md
Changes suggested by Mike, plus a couple of language tweaks.
> [misc] Updating Code submissions

- reference/cli/sailsdebug.md
Mostly changed instances of node-inspector to Node Inspector (this is how its name is formatted in its repository). I left things as-is when formatted as a command.
> [misc] sailsdebug.md updates

- reference/cli/sailsconsole.md
I did a few rephrasing updates, and changed capitalization on a couple of things.
> [misc] sailsconsole.md updates

- reference/cli/sailsnew.md
Capitalization, formatting suggestions for bulleted list.
> [misc] minor changes to sailsnew.md

- reference/cli/sailsversion.md
Just the title, but I'll PR it if you'd rather do the command formatting thing.
> [misc] minor update to sailsversion.md

- reference/sails.config/miscellaneous.md
Aesthetic rephrasing and smooshing together of sentences.
> [misc] minor changes to miscellaneous.md

- reference/blueprint-api/blueprint-api.md
> [misc] blueprint API changes

- reference/application/sails.log.md
> [misc] some doc changes to sails.log()

- reference/application/advanced-usage/lifecycle.md
Sentence case, one minor rewording
> [misc] minor changes to the lifecycle

- reference/application/advanced-usage/advanced-usage.md
Rephrased a thing, changed some punctuation
> [misc] minor changes to Advanced Usage

- upgrading/To1.0.md
> [misc] update update pt 2

- upgrading/upgrading.md
Rewording for flow, minor sentence-casing.
> [misc] upgrading edit

- concepts/ORM/Attributes.md
> [proposal] Update Attributes.md

- reference/waterline/queries/meta.md
> Changed user to newUser

- reference/websockets/sails.io.js/sails.io.js.md
> [misc] several changes to sails.io.js.md

- reference/websockets/sails.sockets/sails.sockets.md
Formatting, some rephrasing that may or may not make sense.
> [misc] changes to sails.sockets.md

- reference/websockets/resourceful-pubsub/subscribe.md
Formatting and some minor rephrasing
> [misc] changes to subscribe.md

- reference/websockets/resourceful-pubsub/resourceful-pubsub.md
> [misc] changes to resourceful-pubsub.md

- reference/waterline/queries/tolerate.md
Formatting
Minor rephrasing of a couple of things, and I removed a sentence that seemed to say the same thing as the following paragraph.
> [misc] changes to tolerate.md

- reference/waterline/queries/populate.md
> [misc] minor changes to populate.md

- reference/waterline/queries/intercept.md
Formatting, a couple of rephrasing suggestions.
> [misc] changes to .intercept.md

- reference/waterline/queries/queries.md
> [misc] changes to queries.md

- reference/waterline/models/query.md
formatting and very minor rephrasing
> [misc] minor changes to .query.md

- reference/waterline/models/validate.md
Formatting, very minor rephrasing
> [misc] changes to .validate.md

- reference/waterline/models/updateOne.md
> [misc] changes to .updateOne.md

- reference/waterline/models/update.md
> [misc] changes to .update.md

- reference/waterline/models/stream.md
> [misc] changes to .stream.md

- reference/waterline/models/replaceCollection.md
Ticks added to title
A formatting
Removed references to an example that had not yet been explained.
> [misc] changes to .replaceCollection.md

- reference/waterline/models/findOrCreate.md
Ticks added to title
Code formatting consistency
Minor rephrasing
> [misc] changes to .findOrCreate.md

- reference/waterline/models/find.md
Ticks added to title
Minor rephrasing
> [misc] minor changes to .find.md

- reference/waterline/models/destroyOne.md
> [misc] changes to .destroyOne.md

- reference/waterline/models/destroy.md
Ticks added to title
Rephrasing
Formatting
> [misc] changes to .destroy.md

- reference/waterline/models/createEach.md
ticks added to title
formatting
rephrasing in a couple of places
> [misc] changes to .createEach.md

- reference/waterline/models/archiveOne.md
ticks, a couple of minor rewords
> [misc] minor changes to .archiveOne.md

- reference/waterline/datastores/sendNativeQuery.md
Minor formatting changes, plus a rephrase.
> [misc] changes to sendNativeQuery.md

- reference/waterline/datastores/datastores.md
Changed a couple of punctuation marks, rephrased a bit.
> [misc] minor changes to datastores.md

- reference/res/res.send.md
formatting, changed a few words
> [misc] minor changes to res.send.md

- reference/res/res.redirect.md
ticks and corrections
suggestion for organizing the Details section
a couple of rephrasings
> [misc] some changes to res.redirect.md

- reference/websockets/sails.io.js/SailsSocket/methods.md
A few formatting changes
Updates for consistency in method descriptions
Some rephrasing for clarity, hopefully
> [misc] changes to methods.md

- reference/res/res.json.md
The usual things, plus some rewording of the Details section for clarity. I may have changed the meaning of this section, so it should be checked for accuracy.
> [misc] changes to res.json.md

- reference/res/res.badRequest.md
Added ticks to title
Modified the opening paragraph to be more clear and specific
Made the tense in the Details section consistent
> [misc] changes to res.badRequest.md

- reference/req/req.param.md
ticks
url => URL
clarification in Example
> [misc] change to req.param()

- reference/req/req.file.md
ticks
rephrasing for clarification
grammar
> [misc] update to req.file()

- reference/req/req.allParams.md
> [misc] update to req.allParams().md

- reference/req/req.acceptsLanguages.md
> [misc] update to req.acceptsLanguages()

- reference/req/req.acceptsCharsets.md
ticks
removed "from the left", as I think this is implied
changed casing in a few places
> [misc] update to req.acceptsCharsets()

- reference/req/req.xhr.md
ticks
Removed a negotiation that seemed like a typo, but I might have been wrong!
> [misc] update to req.xhr.md

- reference/req/req.wantsJSON.md
> [misc] update req.wantsJSON

- reference/req/req.url.md
ticks
added some words
capitalized a url
> [misc] update to req.url

- reference/req/req.signedCookies.md
ticks
base64 encoded => Base64-encoded
added some words
> [misc] req.signedCookies

- reference/req/req.headers.md
the sails => Sails
pre-defined => predefined
Example => Note
+ ticks, of course
> [misc] changes to req.headers.md

- reference/req/req.body.md
ticks
url => URL
slight rephrasing of a part
> [misc] minor changes to req.body.md

- reference/sails.config/sails.config.security.md
> [misc] minor changes to sails.config.security.md

- reference/sails.config/sails.config.models.md
> [misc] minor changes to sails.config.models.md

- reference/sails.config/sails.config.log.md
ticks
capitalization
removed a few words
punctuation
> [misc] minor changes to sails.config.log.md

- reference/sails.config/sails.config.connections.md
Some minor rephrasing and punctuation updates. Ticks.
> [misc] minor changes to sails.config.connections.md

- reference/res/res.attachment.md
Added sync to function signature
> Update res.attachment example

- reference/waterline/datastores/transaction.md
Update broken link to .usingConnection()
> Fix broken link in waterline/datastores/transaction.md

- reference/blueprint-api/Find.md
It was at 2 
but 2 is "drop" for tests
> Update line 114 - Just choose 1 for alter

- concepts/Configuration/Configuration.md
Reference > Configuration url did not include `https://`
> [misc] Fixed documentation url

- reference/cli/sailsgenerate.md
Added a note to `sails generate page` about the web app template.
> [misc] update sailsgenerate.md

- reference/cli/sailsversion.md
To get the version, don't you need a "--"
> [proposal] Shouldn't "--" precede version    [ sails --version]

- reference/sails.config/sails.config.log.md
The example on how to integrate Winston is for an old version of it.
Suggested is an example that works pretty well for me.
> [proposal] Suggested example for new versions of winston

- concepts/Deployment/Hosting.md
> [misc] remove broken links

- concepts/shell-scripts/shell-scripts.md
Minor update to use the user's input, instead of it being hard-coded.
> [proposal] Update shell-scripts.md

- concepts/Blueprints/Blueprint Routes.md
Added in the order found on https://sailsjs.com/documentation/concepts/blueprints/blueprint-actions
> [patch] added missing blueprint action
