- reference/sails.config/sails.config.session.md
On the docs html page for this entry, the "optional values" section is not being formatted correctly, I believe adding this break will fix that.
> Added line break to format correctly for website.

- getting-started/NewToNode.md
Hopefully this will save someone from a headache when they've installed node but "npm doesn't work".
> Instructions for using NPM on FreeBSD

- reference/waterline/models/models.md
There was a link to more information on queries missing from the reference > waterline > models document. The effect was an underlined anchor <a> tag with no href attribute, which was confusing. So, I added in a link to the reference > waterline > queries doc, which seemed like the intended link.
> Added missing hyperlink to anchor

- concepts/ORM/Associations/OnetoOne.md
The *one-to-one* association was referencing the behavior of a one-way association. If I understand correctly, as long as you define a model association on both models, that makes it *one-to-one* (**bidirectional**). If you only define the model in one model that makes it *one-to-one*(**unidirectional**). Maybe I'm misunderstanding something based on [this waterline documenation](https://github.com/balderdashy/waterline-docs/blob/master/associations.md)
> Fixes One-to-one association reference

- anatomy/myApp/config/locales/_README.md.md
They break the website here http://sailsjs.org/#/documentation/anatomy/myApp/config/locales/_README.md.html and are just meaningless.
> Remove redundant backticks

- reference/sails.config/sails.config.http.md
W3C says max-age should be in seconds, Static middleware says it takes milliseconds as the input and output into seconds. Confusing.
> Unit of cache is in milliseconds as opposed to seconds.

- concepts/ORM/Associations/ManytoMany.md
The Many-to-Many example contains an unnecessary `dominant` property which is confusing as the example is  not a cross-adapter/cross-connection association.
> Remove confusing dominant property

- anatomy/myApp/config/sockets.js.md
I was not using authorization before so I am not sure how it should be changed. Migration guide said to use beforeConnect if I was using a custom function before, does this mean it would still be called by authorization parameter, when set to true? If so then I suppose this is the correct change, but I can't be sure since I didn't use this functionality.
> Updated onConnect and onDisconnect to conform to latest version

- concepts/ORM/Validations.md
Added a tiny section on supporting custom validation messages using [sails-hook-validator](https://github.com/lykmapipo/sails-hook-validation)
> Add small section on custom validation message hook

- FAQ.md
A sort guide to deploying Sails.js to Heroku.
> Add "Sails.js and Heroku"

- anatomy/myApp/config/blueprints.js.md
There is no documentation for the `mirror` option.
This has cost me a lot of debugging time in the past.
I would also recommend the default to be true. I suspect most people building client-side apps would assume that behavior of Sails.
> Documented the `mirror` option

- contributing/adapter-specification.md
Documentation for balderdashy/waterline#846
> Add "create" migration to adapter-specification.md

- concepts/0home/0home.md
- reference/0home/0home.md
Plugins subject in reference index links to non existent content. Since generators are explained in CLI section and adapters and hooks appear as concepts, I suggest removing this subject from index, at least until more content about generators, adapters and hooks is written.
> Removed Plugins in reference index

- reference/waterline/models/models.md
While browsing I noticed the create method is missing from the Built-In Model Methods section.
> Add create to the Built-In Model Methods

- concepts/Security/XSS.md
Links look fine in GitHub preview, but are broken (the parentheses are misinterpreted) on http://sailsjs.org/#!/documentation/concepts/Security/XSS.html.
> Fixed broken links to OWASP

- anatomy/myApp/tasks/register/default.js.md
In conjunction with #2814, include information for running custom grunt tasks.
> Update default.js.md for PR #2814

- concepts/Testing/Testing.md
The bootstrap.test.js had sails.lower(done) when it should be Sails.lower(done).
> Fixing a case typo

- reference/sails.config/sails.config.models.md
As per issue https://github.com/balderdashy/waterline/issues/592#issuecomment-113427311
Ability to toggle creation of dynamicFinders has been added, missing in docs.
> Add dynamicFinders

- status/plugins/adapters.js
Hello,
I wrote an adaptor for FileMaker databases.  The semantic interface was all I needed. It is passing all the tests in that interface except for the types that don't apply.  You can't make schema changes with this adaptor.  
Not sure what 'status' should be.  Although it passes the semantic test suite it's still new. There are probably some bugs.
Thanks
Todd
PS. this is my first pull request on github.  not sure if I am doing it correctly :-)
> new adapter for FileMaker Databases

- concepts/extending-sails/Hooks/userhooks.md
The Sails code allows a js file in the `api/hooks` directory without a subfolder. Some users (and myself) might prefer to have the `api/hooks` directory full of files instead of have a bunch of folders with one `index.js` file in them. It seems worth mentioning in the documentation.
> Document api/hooks/file.js alternative

- concepts/Testing/Testing.md
The standard 2000ms is not always long enough to lift Sails. With a timeout in place it is easy to see how to change it if there is a timeout error.
> Increased the timeout in bootstrap.test.js example

- concepts/Testing/Testing.md
Add a note to make the timeout setting in mocha.opts. Otherwise, the test case will always be failing since sails lifting typically completes longer than 2 seconds.
Here is the error I got:
```
1) "before all" hook
0 passing (3s)
1 failing
1)  "before all" hook:
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```
> Add a note to make the timeout setting in mocha.opts

- concepts/Deployment/Hosting.md
OpenShift was missing some important details with their updates (whenever those were). This is now the process needed to run a Sails.js application on OpenShift.
> Updated OpenShift deployment strategy

- reference/waterline/populated-values/add.md
I spent much minutes (so time! wow.) cursing waterline's `add` method.
Why, you ask?
Well, if you attempt to add a record to a collection and that record is already in the collection, waterline throws an error. It's one of those things where someone you love does something and you still love them but why did they do that, you know?
My explanation above was kind of bad, though, so just [see this issue](https://github.com/balderdashy/waterline/issues/352) 
**tl;dr This one's for posterity.** Added a warning to the docs re: the above Issue
> for posterity

- reference/waterline/models/query.md
`return res.ok(results); `
sends back JSON with info about the query and requires different handling than the default responses of the blueprint methods like 
`.find().  `
changing to results.rows produces consistent output.
> Return response in format consistant with .find()

- reference/blueprint-api/Find.md
Hi, 
I've added documentation for the "populate" parameter, which appears to be working for Sails v0.11.0.
Cheers,
Daniel
> Documented the "populate" parameter

- concepts/File Uploads/File Uploads.md
The Amazon S3 and Mongo GridFS links are both invalid.
> The Amazon S3 and Mongo GridFS links!!!

- concepts/ORM/Associations/OnetoMany.md
The name of the javascript files for the two models didn't start with a capital letter causing the example not to work
> Capitalized models js file names

- concepts/Routes/RouteTargetSyntax.md
There's a problem with the parsing of this markdown in the [official documentation page](http://sailsjs.org/documentation/concepts/routes/custom-routes).
The markdown parser render `####Wildcards and dynamic parameters` instead of converting it to an `<h4>` tag.
> add a space to correct the markdown parsing

- reference/waterline/models/findOrCreate.md
@mikermcneil So most of the waterline docs look different than the blueprint api docs. Do you want them to all look the same as the blueprint docs? IE the tables without numbers and the table headers staying consistent?
Other than that, I added a few more ways that this method can be used based on the parameters passed in. Open to feedback. Hope you like it :)
> Starting work on the waterline docs and format

- concepts/ORM/Attributes.md
This will cause errors with valid email addresses for some reason:
type: 'string',
email: true
Instead you should use the following:
type: 'email'
You can reference the following issue for more information on this:
https://github.com/balderdashy/sails/issues/3034
> Correct email example and include missing type

- reference/waterline/queries/populate.md
This solves the confusion around issues like this one:
https://github.com/balderdashy/waterline/issues/1238
> Make usage of the query parameter more explicit in .populate()

- reference/waterline/models/findOrCreate.md
> Fix findOrCreate example

- concepts/ORM/Lifecyclecallbacks.md
This is a simple word change, reflecting that bcrypt is a hashing algorithm, not an encryption algorithm - https://en.wikipedia.org/wiki/Bcrypt
It's a common mistake, as shown in this Stack Overflow answer: https://stackoverflow.com/questions/326699/difference-between-hashing-a-password-and-encrypting-it/326706#326706
> Change terminology usage

- concepts/Sessions/sessions.md
I fixed a few of the headings by adding a space before the heading text.
> Fixed headings on the Sessions concept page

- reference/websockets/sails.io.js/SailsSocket/SailsSocket.md
There was a typo - "autoconnect" was written in lower case but should be in camelCase as it is in the library code.
> fixed autoconnect -> autoConnect

- concepts/Custom Responses/DefaultResponses.md
- reference/res/res.created.md
* created entry on concepts/Custom Responses/DefaultResponses.md for res.created()
* created full reference page on res.created()
> Missing documentation on res.created()

- reference/waterline/populated-values/add.md
Page: http://sailsjs.org/documentation/reference/waterline-orm/populated-values/add
PR that added functionality: https://github.com/balderdashy/waterline/pull/1190/commits/93b45004a1b02c094477c1280c8c8e296ae6b9bc
Waterline docs for reference: https://github.com/balderdashy/waterline-docs/blob/master/models/associations/many-to-many.md#with-an-array-of-new-record
Issue about this line on this page: https://github.com/balderdashy/sails/issues/3733
> Remove note not to try add()ing an array

- reference/waterline/records/save.md
As of v0.12 `*.save(cb)` no longer passes the saved record to the `cb`.
Also, even though recommended, passing a cb to `*.save()` is not strictly Required.
> save.md should reflect changes in sails v0.12

- reference/res/res.created.md
Changed `return res.forbidden(` with `return res.created(` in line 42.
> Fix an error in reference/res/res.created.md

- reference/waterline/models/query.md
replaces #732 
per @rachaelshaw, this commit also links to the doucmentation at sailsjs.org instead of assuming that we'll be able to have relative links that work everywhere.
> in query.md, make the reference to `.native()` a formatted link

- concepts/Custom Responses/AddingCustomResponse.md
I copied the custom response template and tried to implement it, but noticed an error: 
```
`include-all` attempted to `require(/Users/username/Documents/project/api/responses/unauthorized.js)`, but an error occurred:: 
Details:/Users/username/Documents/project/api/responses/unauthorized.js:45
});
^
SyntaxError: Unexpected token )
```
Simply adding a closing bracket solved the problem!
> Add Missing Closing Bracket

- reference/waterline/records/save.md
Starting from version 0.12, .save does not return the newly saved object in the callback.
> Remove misleading .save description

- reference/websockets/sails.io.js/sails.io.js.md
Typo at the end of the paragraph: "io.sais.url"
> Fixes typo in websockets/sails.io.js

- concepts/extending-sails/Generators/generatorList.md
I have created this module and I want to add it to the sailsjs documentation.
Thank you. :+1:
> add sails-inverse-model to List community generators

- concepts/Deployment/Hosting.md
[proposal] Openshift deployment guide updated.
When deploying to OpenShift, Sails Grunt hook should be disabled in `.sailsrc` file. 
All grunt tasks will run by supervisor, before Sails will be lifted. 
First we create file  `.openshift/action_hooks/pre_start_nodejs`
```
#!/bin/bash
export NODE_ENV=production
if [ -f "${OPENSHIFT_REPO_DIR}"/Gruntfile.js ]; then
(cd "${OPENSHIFT_REPO_DIR}"; node_modules/grunt-cli/bin/grunt prod)
fi
```
This will run tasks from /tasks/register/prod.js  every time when server lifts. 
So, we need to disable Grunt hook, to  prevent  task execution again.
> [proposal] Openshift deployment guide updated

- reference/waterline/models/find.md
Documented the already-existing projection feature on find() in a format consistent with the documentation of [populate()](http://sailsjs.com/documentation/reference/waterline-orm/populated-values), etc.
Heads up to @rachaelshaw
> Documented the projection feature on find() page

- concepts/File Uploads/uploading-to-amazon-s3.md
I've been using this example to integrate Amazon S3 into my file uploads. I noticed some commas were missing from the parameters passed in to the req.file.upload call on L20 and L21.
> Fixing missing commas in file upload parameters

- concepts/extending-sails/Generators/generatorList.md
Hi,
I have create a generator for generating handlebars default template.
It works similar to [sails-generate-views-jade](https://github.com/balderdashy/sails-generate-views-jade), but for handlebars.
I have tested and it works completely fine and is very seamless.
> Added sails-generate-views-hbs in the list of generators

- concepts/File Uploads/File Uploads.md
Per the getBaseUrl docs, replaced getBaseUrl() with sails.config.appUrl
http://sailsjs.com/documentation/reference/application/sails-get-base-url
> Replace deprecated getBaseUrl() w/config variable

- concepts/ORM/Models.md
Based on the code, I think that opts is meant to be a "person" object, so I cleaned up the code to that effect so the examples that call the method with a number, or the object will presumably work correctly.
> Modify example to fix syntax and a minor bug

- concepts/Deployment/Hosting.md
Added an official quickstart, the official guides, and a "getting started" article to the list of "using" guides, under the "Hosting" section of the docs.
> Added nanobox to the list of 'using' guides

- reference/req/req.md
The link to the request object (i.e. the link back to this page) was broken, this is the fix
> Update req.md - Fixed link

- reference/waterline/models/create.md
removed a closing parentheses.
> waterline/models/create.md redundant: remove a closing parentheses

- reference/req/req.file.md
In the example for the `req.file()` documentation, the variable `files` is undefined inside the callback to `upload()`.
> Fix variable name from `files` to uploadedFiles

- concepts/Deployment/Hosting.md
- faq/faq.md
This was already merged into master with #875. This is just an update to the nanobox hosting guides, and also adds nanobox to the faq guides section.
> updated nanobox hosting docs. added nanobox to faq guides

- concepts/File Uploads/uploading-to-amazon-s3.md
Official AWS S3 docs (http://docs.aws.amazon.com/general/latest/gr/rande.html) says:
> Amazon S3 renamed the US Standard Region to the US East (N. Virginia) Region to be consistent with AWS regional naming conventions.
> "US Standard" is not the name of the region anymore

- concepts/Views/ViewEngines.md
This is covered in the upgrade docs @ https://github.com/balderdashy/sails-docs/blob/1.0/upgrading/To1.0.md but a new project may not go looking there.
> v1.0: In view engines conceptual docs: Mention `consolidate` needs to be installed in order to use a view engine other than `ejs`

- anatomy/views/homepage.ejs.md
- anatomy/views/layout.ejs.md
- concepts/Views/ViewEngines.md
- concepts/Views/Views.md
This includes the new website (the old one is heavily broken and no longer relevant as it only applies to v1) and new code repository (which apparently changed on account of EJS v2).
> Update URLs to new EJS locations

- concepts/ORM/Lifecyclecallbacks.md
Clear advice about making sure thrown errors or rejections make it back to the callback and why.
> Update Lifecyclecallbacks.md with error handling

- anatomy/api/models/User.js.md
Normal quotes were used instead of backticks surrounding a command. Therefore MarkDown rendered this as regular text instead of a command.
> Fixed command showing as regular text

- concepts/Blueprints/Blueprint Routes.md
In another docs page it's implied that CSRF is not enabled by default though. Either documentation or default config should be updated.
https://next.sailsjs.com/documentation/concepts/security/csrf
> A note about CSRF in default config

- concepts/ActionsAndControllers/RoutingToActions.md
Unless I'm mistaken, the action would have to be named `make` and not `makeIt`.
> Fix action name in docs

- reference/application/advanced-usage/sails.lower.md
* Remove note about `lowered` event being sent as there is no such event.
* Add note about `lower` event being sent *before* shutting down HTTP/WebSocket services.
> Fix event documentation for `lower`

- concepts/Logging/Logging.md
Action is described in the document as "make" but is referred to currently as "makeIt" in one spot of the description.
>  Fixed typo in routing actions description

- concepts/ORM/model-settings.md
This issue was brought up in the sails gitter channel on may 30th. Mike asked if someone could add this note.
> customToJSON does not support async functions

- reference/application/advanced-usage/sails.request.md
Dict keys with hyphens need to be quoted.
> docs: add quotes to key in headers example dict

- concepts/Helpers/Helpers.md
- concepts/ORM/Models.md
updated: 1.0 -> v1.0
On same doc, there's another place where it is simply "v1.0"
This change just makes both of them "v1.0" now
Also "Javascript" -> "JavaScript"
> Edited Sails versioning for consistency

- reference/sails.config/sails.config.i18n.md
Should specify locales & their translation files must be lowercase. 
Expected a case-insensitive match on browsers sending `Accept-Language` headers with a region (ie, `zh-TW` for Chinese as used in Taiwan vs. `zh` for 'any old' Chinese), and after much head-banging realised this isn't the case as the browsers headers are lowercased somewhere along the way.
> Update sails.config.i18n.md: specificity

- reference/waterline/models/update.md
The link to 'update-one' is outdated. This change should redirect the user to the correct page.
> Fix link to 'update-one'-method

- concepts/ORM/ORM.md
Without putting the database name the connection is going to work, as I experienced
> Database name should be present

- reference/websockets/sails.io.js/sails.io.js.md
Fixed a broken URL it was missing the `https://`, so was being treated an an internal URL, rather than a URL to an external site
> Fix broken URL

- reference/cli/sailslift.md
Capitalized the first word in the title. 
I would guess that Sails is lowercase in the title because it refers to a command-line command. I've been formatting it in sentence case in my updates, but we could instead use the ticks to format the title as a command and leave everything lowercase. Let me know if that would be better, and I can go back in and reformat the titles within the Command-line interface section.
> [misc] minor change to sailslift.md, and a question

- concepts/ORM/model-settings.md
This PR fixes the broken link to datastore configuration on the model settings page
- The two links on this screenshot below lead to 404 page
> [patch] Fix broken link in concept/ORM/model-settings.md

- concepts/Assets/DefaultTasks.md
Since built-in support for CoffeeScript and JST things has been removed, I've removed the documentation talking about that feature. I'll keep an eye out for other mentions of CoffeeScript and JST support.
> [misc] removed CoffeeScript and JST mentions

- reference/res/res.cookie.md
Ticks added to title.
In Details, removed the reference to "the previous example", which doesn't seem to exist. 
It seems like a lot of the terms in double quotes should be in ticks, based on how I've seen them (double quotes and ticks) used in the docs thus far.
I think that bodyParser() middleware is referring to the Express body-parsing middleware, so I made that explicit. 
Reworded a couple of things for clarity and flow.
> [misc] changes to res.cookie.md

- concepts/ORM/Querylanguage.md
The `where` clause of this query contains
a `!` modifier (for `name`).  But as of Sails v1.0,
this modifier is deprecated.  (Please use `!=` instead.)
> This backwards compatibility may be removed
> in a future release of Sails/Waterline.  If this usage
> is left unchanged, then queries like this one may eventually
> fail with an error.
> In Sails v1.0, the `!` modifier is deprecated.

- concepts/ORM/Associations/ThroughAssociations.md
The via should reference the through model attribute and not the association model attribute
> Correcting the via

- concepts/Testing/Testing.md
[Scalability](https://sailsjs.com/documentation/concepts/deployment/scalability) reference on the [testing](https://sailsjs.com/documentation/concepts/testing) page is wrong (404 Not Found).
`documentation/concepts/deployment/scalability` changed to `documentation/concepts/deployment/scaling`
> [misc] Fix wrong reference to scaling page

- concepts/ORM/Associations/ManytoMany.md
- concepts/ORM/Associations/OneWayAssociation.md
- concepts/ORM/Associations/OnetoMany.md
- concepts/ORM/Associations/ThroughAssociations.md
Before, all references pointed to a [non-existent page](https://sailsjs.com/documentation/reference/waterline-orm/query/populate), giving a 404 error to the user.
The [docs for this exist](https://sailsjs.com/documentation/reference/waterline-orm/queries/populate) and its URL was a little different from the one that was pointed.
I just fixed it :smiley:
> [misc] Fixed the `populate` method references

- reference/req/req.socket.md
- sails.sockets.* [here](https://sailsjs.com/documentation/reference/request-req/req-socket) points to a link that is 
broken. 
- Added correct link in the documentation.
> [patch] Broken link

- concepts/Internationalization/Locales.md
Fixed the typo. After testing, I figured that 'req.i18n' is the one that works instead of 'res'.
> [misc] Updated Locales.md typo found

- reference/waterline/queries/limit.md
> [misc] - Fixed query example

- concepts/Blueprints/Blueprint Actions.md
**Node version**: 12.16.3
**Sails version** _(sails)_: 1.2.4
**ORM hook version** _(sails-hook-orm)_: 2.1.1
**Sockets hook version** _(sails-hook-sockets)_: 2.0.0
**Organics hook version** _(sails-hook-organics)_: 
**Grunt hook version** _(sails-hook-grunt)_: 
**Uploads hook version** _(sails-hook-uploads)_: 
**DB adapter & version** _(e.g. sails-mysql@5.55.5)_: 
**Skipper adapter & version** _(e.g. skipper-s3@5.55.5)_: 
<hr/>
I was unable to override the Blueprint findOne action as suggested here https://sailsjs.com/documentation/concepts/blueprints/blueprint-actions#?overriding-blueprint-actions
`/api/controllers/requests/find.js` works correctly in overriding the default but my file created at `/api/controllers/requests/find-one.js` did not. I've tried naming it to "findone.js" and it …
> [patch] Update Blueprint Actions.md

- concepts/extending-sails/Adapters/adapterList.md
The text had a typo "depoyment" and I changed it to "deployment"
> [patch] Fix typo on mongodb example on adapters page

- concepts/Views/Layouts.md
View Engines link had an invalid path. Updated from`/documentation/concepts/concepts/views/view-engines` to `/documentation/concepts/views/view-engines`
> [patch] Updated Layouts.md - fixed a broken link
